version: "3"
services:
  my-node-app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    # environment:
    #   - PORT=3000
